### ISSUE TITLE
 docs(pt): translate `guide/extras/reactivity-in-depth.md`

### ISSUE THREAD

**Issue by viniciusdeliz** [nazarepiedady/vue3-docs-pt#33]

**Comment by nazarepiedady** [comment]
A tradução do presente documento está sobre a responsabilidade do @nazarepiedady

**Comment by viniciusdeliz** [comment]
@nazarepiedady is this document or any other document available for translation?

**Comment by nazarepiedady** [comment]
@viniciusdeliz I am already translating this document!

If you are still available to contribute,
the API folder received a huge update in its original version in English,
you could start to update the translated content inside that folder and
create an issue for each document translated. What do you think?

I believe that will not be a huge effort because the majory part is already made.

**Comment by viniciusdeliz** [comment]
@nazarepiedady while trying to synch this branch and the original [vuejs/docs](https://github.com/vuejs/docs) I noticed that [vue3-docs-pt](https://github.com/nazarepiedady/vue3-docs-pt/) branch isn't even a fork from the original docs. Why is that? That decision now increases the complexity of keeping everything synchronized.

**Comment by nazarepiedady** [comment]
@viniciusdeliz the main branch will not be discarded because it follows the translation pattern practiced on the currently translated documentation that can be found in the [vue-translations](https://github.com/vuejs-translations/) organization. None of the projects there are forks of the original documentation, and they are updated independently.

I acknowledge your work but I think should consult the translated versions that already exist to see what pattern they are following.

I used the same pattern to produce the Portuguese translation for the [vitejs/docs-pt](https://github.com/vitejs/docs-pt)

I will close this issue because the translation of this document were already finished.
